### ISSUE TITLE
Testing WxReceiver without weewx driver

### ISSUE THREAD

**Issue by agrodev** [kobuki/VPTools#7]
Hello Kobuki, first of all thanks for your work. I'm not sure if this is the correct channel to ask my question. 

I am testing WxReceiver, I have a Davis VUE and an Arduino Pro Mini wired with an RFM69 and some BMP180 and BMP280, I am in Spain using the European band. ISSRx sketch and SFE_180 sample sketch work for me. 

raw:50-03-38-FF-71-00-C3-67-FF-FF station:0 packets:20/0/100.00 channel:1 rssi:-36 batt:ok windv:3 winddraw:56 windd:83 rainsecs:-1 fei:-1 delta:2562456 
raw:80-02-38-31-29-0E-96-AC-FF-FF station:0 packets:21/0/100.00 channel:2 rssi:-36 batt:ok windv:2 winddraw:56 windd:83 temp:78.6 fei:9 delta:2562456 
raw:20-04-38-D5-81-85-72-C4-FF-FF station:0 packets:22/0/100.00 channel:3 rssi:-36 batt:ok windv:4 winddraw:56 windd:83 vcap:2.8 fei:-6 delta:2562392 

With WxReceiver I get in the console:

WxReceiver v2019122001 ready to accept commands
?
ERR
ERR bad command
ERR bad command

What are the expected commands? Should the sketch work without weewx? Can i check it somehow?

Thanks in advance.

**Comment by kobuki** [comment]
The data flow should look something like this:
```
# WxReceiver v2019122001 ready to accept commands
>?
# OK t1 f1 o0 m1 x190 r0 stopped
>t3
# OK listening to 1 2
>m1
# OK band EU
>?
# OK t3 f1 o0 m1 x190 r0 running
I 102 51 01 90 FF 73 00 CB 93  -67 0 10
I 103 41 01 90 00 03 00 16 2D  -74 2625024 -6
I 104 81 01 90 FF C3 00 71 2A  -68 2625012 4
I 103 50 00 00 FF 75 00 48 5B  -84 506256 -6
B 0 0 215 99738 0 0
I 100 E1 01 90 80 03 00 CC 5F  -68 2625032 -11
...
```
Lines starting with '>' are not displayed in the serial console, but typed in. Make sure you send CR+LF or any of the 2 codes after each command sent. I usually use miniterm or miniterm.py on linux, that works just fine for simple tests. Otherwise, the sketch is compatible with either the Meteostick driver or https://github.com/kobuki/weewx-meteoRX (I suggest the latter for my sketch as it contains a lot of fixes and small enhancements).

Commands are not documented, please look into the source for that. They should still be compatible with the Meteostick WeeWx driver, though, so the docs for that might provide adequate guidance. If you're stuck, you can ask here.

**Comment by agrodev** [comment]
I'm on Mac, I was using the Arduino serial console and for some reason I wasn't sending the messages correctly. I have installed another serial console and now I can write the commands and I receive the data flow correctly. I'm going to try to install weewx and test your driver.

Thank you.
